name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use the Node.js version that suits your project

      - name: Install Dependencies
        run: npm install # If your project uses npm

      - name: Build
        run: npm run build # Replace with your build command (e.g., `hugo` for Hugo, `gatsby build` for Gatsby)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Replace with your build output folder (e.g., public, build, docs)
          publish_branch: gh-pages # The branch to deploy to